### ISSUE TITLE
Cannot open a connection

### ISSUE THREAD

**Issue by labordep** [pharo-rdbms/Pharo-SQLite3#107]
When I'm trying to use the library to read a .db file, I have an exception.

![image](https://github.com/pharo-rdbms/Pharo-SQLite3/assets/49183340/a1e7a673-baaa-4724-9704-49d266839ad2)

My example:

```smalltalk
connection := SQLite3Connection on: (FileLocator desktop / 'ownership_database.db') fullName.
connection open.
```

My file `ownership_database.db` is with the head "SQLite format 3".

My config:
- Pharo-11.0.0+build.721
- VM 10.0.9
- Windows 11 Pro 64bits

**Comment by labordep** [comment]
I am a complete beginner in this area. I have the /bin files for Windows. Do I need to take any specific actions with them?

**Comment by MOSpok** [comment]
Hi, I had the same issue. On my side, the cause was that the dll was not found because its directory was not in the PATH environment variable and because it searches for 'sqlite3' instead of 'sqlite3.dll'. 
You can test if it is the issue by running into the playground : `finder := FFIWindowsLibraryFinder new.
finder findLibrary: 'sqlite3'.
Transcript show: finder paths "to check the paths it is seaching in" `
I resolved the issue by adding the location to my PATH env var (something like` Pharo 11.0 - 64bit (stable)\pharo-local\iceberg\pharo-rdbms\Pharo-SQLite3\bin\windows\64bit` ) and copying the dll without the '.dll'. 
![image](https://github.com/pharo-rdbms/Pharo-SQLite3/assets/113245455/5eb1b35d-61c3-4524-b308-e14a06a4e2f5)
After restarting the launcher and image to be up to date,it was running fine.

**Comment by astares** [comment]
On Windows the DLL is required. It is included in the "bin" folder when the project is cloned locally. Just open the local git project folder from Iceberg using "Extra" -> "Open in native file browser"

<img width="1021" alt="image" src="https://github.com/pharo-rdbms/Pharo-SQLite3/assets/5980033/3cf57165-9a64-4218-b50e-221afe8ec7b1">

Ideally copy the DLL into the directory of the virtual machine (pharo.exe) you are using so they could be found. You can easily open this one:

```Smalltalk
Smalltalk vmDirectory asFileReference openInOSFileBrowser 
```

As an alternative you can also downloaded latest precompiled version from https://www.sqlite.org/download.html 

Additionally I recommend to download from the same page the [sqlite-tools-win-x64-3450200.zip](https://www.sqlite.org/2024/sqlite-tools-win-x64-3450200.zip) which includes nice command line tools like sqlite3.exe or a diff tool. (see https://www.sqlite.org/cli.html where this one is explained)

If you do more work with SQLite I can recommend to use a visual DB browser like https://sqlitebrowser.org

Hope that helps
